name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: Frontend
        fetch-depth: 0
        persist-redentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    - name: Checkout backend
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: prasenjit52282/testing
        path: Backend

    - name: list
      run: ls

    - name: list-front
      run: |
        cd Frontend
        ls

    - name: list-back
      run: |
      cd Backend
      ls