name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: frontend
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    - name: Checkout backend
      uses: actions/checkout@v2
      with:
        repository: prasenjit52282/testing
        path: backend
    
    - name: list
      run: ls

    - name: list-front
      run: |
        cd frontend
        ls

    - name: list-back
      run: |
        cd backend
        ls

    # - name: Commit files
    #   run: |
    #     date > generated.txt
    #     git config --local user.name the-it-weirdo
    #     git config --local user.email ddsmegh4@gmail.com
    #     git add .
    #     git commit -m "generated via gh action"
    #     git branch -M main
    #   continue-on-error: true

    # - name: GitHub Push
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.PAT }}
    #     branch: 'main'
    #     force: true
    #     repository: 'prasenjit52282/testing'