name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    - name: List files
      run : ls

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    # - run: ssh -T git@github.com

    - name: Commit files
      run: |
        date > generated.txt
        git config --global user.name the-it-weirdo
        git config --global user.email ddsmegh4@gmail.com
        git add .
        git commit -m "generated via gh action"
        git branch -M main
      continue-on-error: true


    - name: Push files
      run: |
        git remote add other https://the-it-weirdo:9de3b9cf3a029b1bc891c8ad767b083288ea84a8@github.com/the-it-weirdo/learning-gh-actions.git
        git push other main --force

    # - name: Commit & Push changes
    #   uses: actions-js/push@master
    #   with:
    #     author_email: ddsmegh4@gmail.com
    #     author_name: the-it-weirdo
    #     github_token: "9de3b9cf3a029b1bc891c8ad767b083288ea84a8"
    #     force: true
    #     empty: true
    #     branch: "main"
    #     message: "push by gh action"
    #     repository: "the-it-weirdo/learning-gh-actions"

    # - name: Pull files from other self
    #   run: |
    #     git remote add rem https://github.com/the-it-weirdo/learning-gh-actions
    #     git pull --no-commit --rebase rem main

    # - name: GitHub Push to  other repo owner self
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     repository: the-it-weirdo/learning-gh-actions
    #     branch: 'main'
    #     force: true
    #     github_token: ${{ secrets.PUSH_SECRET }}
    #   continue-on-error: true

    # - name: GitHub Push to  other owner
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     repository: prasenjit52282/testing
    #     branch: 'main'
    #     github_token: ${{ secrets.gh-action-push-to-other }}
    #   continue-on-error: true
