name: CI

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run
      id: run
      run: |  
        ls
        date > generated.txt
        git config user.name the-it-weirdo
        git config user.email ddsmegh4@gmail.com
        git add .
        git commit -m "generated via gh action"
        git branch -M main
        git push -u https://github.com/the-it-weirdo/learning-gh-actions.git main
      continue-on-error: true
