name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    - name: List files
      run : ls

    - name: Commit files
      run: |
        date > generated.txt
        git config --local user.name the-it-weirdo
        git config --local user.email ddsmegh4@gmail.com
        git add .
        git commit -m "generated via gh action"
        git branch -M main
      continue-on-error: true

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: 'main'
        force: true
        repository: 'prasenjit52282/testing'