name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    - name: List files
      run : ls

    - name: Commit files
      run: |
        date > generated.txt
        git config user.name the-it-weirdo
        git config user.email ddsmegh4@gmail.com
        git add .
        git commit -m "generated via gh action"
      continue-on-error: true

    - name: Pull files from other self
      run: |
        git remote add rem https://github.com/the-it-weirdo/learning-gh-actions
        git pull --no-commit rem

    - name: GitHub Push to  other repo owner self
      uses: ad-m/github-push-action@v0.6.0
      with:
        repository: the-it-weirdo/learning-gh-actions
        branch: 'main'
        github_token: ${{ secrets.gh-action-push-to-other }}
      continue-on-error: true

    # - name: GitHub Push to  other owner
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     repository: prasenjit52282/testing
    #     branch: 'main'
    #     github_token: ${{ secrets.gh-action-push-to-other }}
    #   continue-on-error: true
